"""create submissions table

Revision ID: 56d9f9be9be7
Revises: 
Create Date: 2026-07-22 15:12:56.667589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate renders custom column types by their fully-qualified name (e.g.
# app.core.db_types.UTCDateTime) but does not emit the import for them, which
# fails at migration time with NameError. Importing the module here covers every
# generated revision.
import app.core.db_types


# revision identifiers, used by Alembic.
revision: str = '56d9f9be9be7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', app.core.db_types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('sentiment', sa.String(length=16), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('ai_reply', sa.Text(), nullable=True),
    sa.Column('ai_provider', sa.String(length=32), nullable=True),
    sa.Column('ai_status', sa.String(length=16), nullable=False),
    sa.Column('ai_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index('ix_submissions_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_submissions_email', ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index('ix_submissions_email')
        batch_op.drop_index('ix_submissions_created_at')

    op.drop_table('submissions')
    # ### end Alembic commands ###
